name: Deploy to Netlify (Advanced)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      skip_version_update:
        description: 'Skip version update'
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Update manifest version
        if: ${{ !inputs.skip_version_update }}
        run: npm run update-manifest
      
      - name: Build application
        run: npm run build
      
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions - Version ${{ github.sha }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      
      - name: Commit updated manifest
        if: ${{ !inputs.skip_version_update }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/manifest.json
          git diff --staged --quiet || git commit -m "Auto-update manifest version [skip ci]"
          git push
      
      - name: Notify deployment success
        if: success()
        run: |
          echo "✅ Deployment erfolgreich abgeschlossen!"
          echo "🔗 Site URL: https://${{ secrets.NETLIFY_SITE_ID }}.netlify.app"
      
      - name: Notify deployment failure
        if: failure()
        run: |
          echo "❌ Deployment fehlgeschlagen!"
          echo "Bitte überprüfe die Logs für Details."
